# Generated by Django 4.2.2 on 2023-06-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoclass',
            name='createdOn',
        ),
    ]
