# Generated by Django 4.2.2 on 2023-06-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0003_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
